## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('full', ['network', 'propagation','network', 'internet', 'applications'])
    module.source = [
        'model/full-wifi-information-element.cc',
        'model/full-wifi-information-element-vector.cc',
        'model/full-wifi-channel.cc',
        'model/full-wifi-mode.cc',
        'model/full-ssid.cc',
        'model/full-wifi-phy.cc',
        'model/full-wifi-phy-state-helper.cc',
        'model/full-error-rate-model.cc',
        'model/full-yans-error-rate-model.cc',
        'model/full-nist-error-rate-model.cc',
        'model/full-dsss-error-rate-model.cc',
        'model/full-interference-helper.cc',
        'model/full-yans-wifi-phy.cc',
        'model/full-yans-wifi-channel.cc',
        'model/full-wifi-mac-header.cc',
        'model/full-wifi-mac-trailer.cc',
        'model/full-mac-low.cc',
        'model/full-wifi-mac-queue.cc',
        'model/full-mac-tx-middle.cc',
        'model/full-mac-rx-middle.cc',
        'model/full-dca-txop.cc',
        'model/full-supported-rates.cc',
        'model/full-capability-information.cc',
        'model/full-status-code.cc',
        'model/full-mgt-headers.cc',
        'model/full-random-stream.cc',
        'model/full-dcf-manager.cc',
        'model/full-wifi-mac.cc',
        'model/full-regular-wifi-mac.cc',
        'model/full-wifi-remote-station-manager.cc',
        'model/full-ap-wifi-mac.cc',
        'model/full-sta-wifi-mac.cc',
        'model/full-adhoc-wifi-mac.cc',
        'model/full-wifi-net-device.cc',
        'model/full-arf-wifi-manager.cc',
        'model/full-aarf-wifi-manager.cc',
        'model/full-ideal-wifi-manager.cc',
        'model/full-constant-rate-wifi-manager.cc',
        'model/full-amrr-wifi-manager.cc',
        'model/full-onoe-wifi-manager.cc',
        'model/full-rraa-wifi-manager.cc',
        'model/full-aarfcd-wifi-manager.cc',
        'model/full-cara-wifi-manager.cc',
        'model/full-minstrel-wifi-manager.cc',
        'model/full-qos-tag.cc',
        'model/full-qos-utils.cc',
        'model/full-edca-txop-n.cc',
        'model/full-msdu-aggregator.cc',
        'model/full-amsdu-subframe-header.cc',
        'model/full-msdu-standard-aggregator.cc',
        'model/full-originator-block-ack-agreement.cc',
        'model/full-dcf.cc',
        'model/full-ctrl-headers.cc',
        'model/full-qos-blocked-destinations.cc',
        'model/full-block-ack-agreement.cc',
        'model/full-block-ack-manager.cc',
        'model/full-block-ack-cache.cc',
        'helper/full-athstats-helper.cc',
        'helper/full-wifi-helper.cc',
        'helper/full-yans-wifi-helper.cc',
        'helper/full-nqos-wifi-mac-helper.cc',
        'helper/full-qos-wifi-mac-helper.cc',
        'helper/full-duplex-library.cc',
        ]

    module_test = bld.create_ns3_module_test_library('full')
    module_test.source = [
        'test/full-block-ack-test-suite.cc',
        'test/full-dcf-manager-test.cc',
        'test/full-tx-duration-test.cc',
        'test/full-wifi-test.cc',
        ]

    # headers = bld.new_task_gen(features=['ns3header'])
    headers = bld(features='ns3header') 
    headers.module = 'full'
    headers.source = [
        'model/full-wifi-information-element.h',
        'model/full-wifi-information-element-vector.h',
        'model/full-wifi-net-device.h',
        'model/full-wifi-channel.h',
        'model/full-wifi-mode.h',
        'model/full-ssid.h',
        'model/full-wifi-preamble.h',
        'model/full-wifi-phy-standard.h',
        'model/full-yans-wifi-phy.h',
        'model/full-yans-wifi-channel.h',
        'model/full-wifi-phy.h',
        'model/full-interference-helper.h',
        'model/full-wifi-remote-station-manager.h',
        'model/full-ap-wifi-mac.h',
        'model/full-sta-wifi-mac.h',
        'model/full-adhoc-wifi-mac.h',
        'model/full-arf-wifi-manager.h',
        'model/full-aarf-wifi-manager.h',
        'model/full-ideal-wifi-manager.h',
        'model/full-constant-rate-wifi-manager.h',
        'model/full-amrr-wifi-manager.h',
        'model/full-onoe-wifi-manager.h',
        'model/full-rraa-wifi-manager.h',
        'model/full-aarfcd-wifi-manager.h',
        'model/full-cara-wifi-manager.h',
        'model/full-minstrel-wifi-manager.h',
        'model/full-wifi-mac.h',
        'model/full-regular-wifi-mac.h',
        'model/full-wifi-phy.h',
        'model/full-supported-rates.h',
        'model/full-error-rate-model.h',
        'model/full-yans-error-rate-model.h',
        'model/full-nist-error-rate-model.h',
        'model/full-dsss-error-rate-model.h',
        'model/full-wifi-mac-queue.h',
        'model/full-dca-txop.h',
        'model/full-wifi-mac-header.h',
        'model/full-qos-utils.h',
        'model/full-edca-txop-n.h',
        'model/full-msdu-aggregator.h',
        'model/full-amsdu-subframe-header.h',
        'model/full-qos-tag.h',
        'model/full-mgt-headers.h',
        'model/full-status-code.h',
        'model/full-capability-information.h',
        'model/full-dcf-manager.h',
        'model/full-mac-rx-middle.h', 
        'model/full-mac-low.h',
        'model/full-originator-block-ack-agreement.h',
        'model/full-dcf.h',
        'model/full-ctrl-headers.h',
        'model/full-block-ack-agreement.h',
        'model/full-block-ack-manager.h',
        'model/full-block-ack-cache.h',
        'helper/full-athstats-helper.h',
        'helper/full-wifi-helper.h',
        'helper/full-yans-wifi-helper.h',
        'helper/full-nqos-wifi-mac-helper.h',
        'helper/full-qos-wifi-mac-helper.h',
        'helper/full-duplex-library.h',
        ]

    if bld.env['ENABLE_GSL']:
        module.use.extend(['GSL', 'GSLCBLAS', 'M'])
        module_test.use.extend(['GSL', 'GSLCBLAS', 'M'])

    # if (bld.env['ENABLE_EXAMPLES']):
    #     bld.add_subdirs('examples')
    if bld.env.ENABLE_EXAMPLES:bld.recurse('examples')

    bld.ns3_python_bindings()

